blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/rsheptolut/TaskTimerWidgetR/discussions
    about: Ask questions or start a discussion about Task Timer Widget R.
